#ifndef _INCLUDE_LEFT4DOWNTOWN_EXTENSION_CONFIG_H_
#define _INCLUDE_LEFT4DOWNTOWN_EXTENSION_CONFIG_H_

#if defined GENERATED_BUILD
# include <left4downtown_version_auto.h>
# define SMEXT_CONF_VERSION       LEFT4DOWNTOWN_VERSION_STRING
#else
# define SMEXT_CONF_VERSION       "1.0.0"
#endif

#define SMEXT_CONF_NAME           "Left 4 Downtown Redux"
#define SMEXT_CONF_DESCRIPTION    "Extention for L4D1/2"
#define SMEXT_CONF_AUTHOR         "Kiwi, JeremyDF93"
#define SMEXT_CONF_URL            "http://praisethemoon.com/"
#define SMEXT_CONF_LOGTAG         "L4D"
#define SMEXT_CONF_LICENSE        "GPL"
#define SMEXT_CONF_DATESTRING     __DATE__


#define SMEXT_LINK(name) SDKExtension *g_pExtensionIface = name;

#define SMEXT_CONF_METAMOD

#define SMEXT_ENABLE_FORWARDSYS
//#define SMEXT_ENABLE_HANDLESYS
#define SMEXT_ENABLE_PLAYERHELPERS
//#define SMEXT_ENABLE_DBMANAGER
#define SMEXT_ENABLE_GAMECONF
//#define SMEXT_ENABLE_MEMUTILS
#define SMEXT_ENABLE_GAMEHELPERS
//#define SMEXT_ENABLE_TIMERSYS
//#define SMEXT_ENABLE_THREADER
//#define SMEXT_ENABLE_LIBSYS
//#define SMEXT_ENABLE_MENUS
//#define SMEXT_ENABLE_ADTFACTORY
#define SMEXT_ENABLE_PLUGINSYS
//#define SMEXT_ENABLE_ADMINSYS
//#define SMEXT_ENABLE_TEXTPARSERS
//#define SMEXT_ENABLE_USERMSGS
//#define SMEXT_ENABLE_TRANSLATOR
//#define SMEXT_ENABLE_ROOTCONSOLEMENU

#endif // _INCLUDE_LEFT4DOWNTOWN_EXTENSION_CONFIG_H_
